"""empty message

Revision ID: 8bf74f3078e2
Revises: 
Create Date: 2021-07-06 12:05:24.207029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf74f3078e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('postID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('postID')
    )
    op.create_table('projects',
    sa.Column('projectID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('shortDescription', sa.String(length=35), nullable=True),
    sa.Column('gif', sa.String(), nullable=True),
    sa.Column('videoUrl', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('githubURL', sa.String(), nullable=True),
    sa.Column('demoURL', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('projectID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('post')
    # ### end Alembic commands ###
